/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Marco
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        barraMenu = new javax.swing.JMenuBar();
        menuPaciente = new javax.swing.JMenu();
        crearPaciente = new javax.swing.JMenuItem();
        consultarPaciente = new javax.swing.JMenuItem();
        menuEjercicios = new javax.swing.JMenu();
        acercade = new javax.swing.JMenu();
        salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fitness");

        escritorio.setBackground(new java.awt.Color(153, 255, 255));
        escritorio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        escritorio.setForeground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 675, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 319, Short.MAX_VALUE)
        );

        barraMenu.setBackground(new java.awt.Color(0, 102, 102));
        barraMenu.setBorder(null);
        barraMenu.setForeground(new java.awt.Color(0, 102, 102));
        barraMenu.setBorderPainted(false);

        menuPaciente.setBackground(new java.awt.Color(0, 102, 102));
        menuPaciente.setForeground(new java.awt.Color(255, 255, 255));
        menuPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/paciente.png"))); // NOI18N
        menuPaciente.setText("Paciente");
        menuPaciente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuPaciente.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N

        crearPaciente.setBackground(new java.awt.Color(204, 102, 0));
        crearPaciente.setText("Crear Paciente");
        menuPaciente.add(crearPaciente);

        consultarPaciente.setBackground(new java.awt.Color(204, 102, 0));
        consultarPaciente.setText("Consultar Usuario");
        consultarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarPacienteActionPerformed(evt);
            }
        });
        menuPaciente.add(consultarPaciente);

        barraMenu.add(menuPaciente);

        menuEjercicios.setBackground(new java.awt.Color(0, 102, 102));
        menuEjercicios.setForeground(new java.awt.Color(255, 255, 255));
        menuEjercicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ejercicio.png"))); // NOI18N
        menuEjercicios.setText("Ejercicios");
        menuEjercicios.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        barraMenu.add(menuEjercicios);

        acercade.setBackground(new java.awt.Color(0, 102, 102));
        acercade.setForeground(new java.awt.Color(255, 255, 255));
        acercade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/acerca de.jpg"))); // NOI18N
        acercade.setText("Acerca de");
        acercade.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        barraMenu.add(acercade);

        salir.setBackground(new java.awt.Color(0, 102, 102));
        salir.setForeground(new java.awt.Color(255, 255, 255));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/salir.jpg"))); // NOI18N
        salir.setText("Salir");
        salir.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        barraMenu.add(salir);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu acercade;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem consultarPaciente;
    private javax.swing.JMenuItem crearPaciente;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu menuEjercicios;
    private javax.swing.JMenu menuPaciente;
    private javax.swing.JMenu salir;
    // End of variables declaration//GEN-END:variables
}
