/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Marco
 */
public class VentanaVerMedidas extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaMedidas
     */
    public VentanaVerMedidas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAgregarMedidas = new javax.swing.JPanel();
        lblEstatura = new javax.swing.JLabel();
        fieldEstatura = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        fieldPeso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblPliegues = new javax.swing.JLabel();
        lblTricep = new javax.swing.JLabel();
        fieldTricep = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lblSubescapular = new javax.swing.JLabel();
        fieldSubescapular = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        lblAbdomen = new javax.swing.JLabel();
        fieldAbdomen = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lblIliaco = new javax.swing.JLabel();
        fieldIliaco = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        lblMuslo = new javax.swing.JLabel();
        fieldMuslo = new javax.swing.JTextField();
        fieldPectoralH = new javax.swing.JTextField();
        fieldPantorrilla = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lblPantorrilla = new javax.swing.JLabel();
        lblPectoralH = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblCircunferencias = new javax.swing.JLabel();
        lblCuello = new javax.swing.JLabel();
        fieldCuello = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        lblBicepDer = new javax.swing.JLabel();
        fieldBicepDer = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        lblBicepIzq = new javax.swing.JLabel();
        fieldBicepIzq = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        lblPectoral = new javax.swing.JLabel();
        fieldPectoral = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        lblEspalda = new javax.swing.JLabel();
        fieldEspalda = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        lblCintura1 = new javax.swing.JLabel();
        fieldCintura1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        lblCintura2 = new javax.swing.JLabel();
        fieldCintura2 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        lblCintura3 = new javax.swing.JLabel();
        fieldCintura3 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        lblCadera = new javax.swing.JLabel();
        fieldCadera = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        lblMusloDer = new javax.swing.JLabel();
        fieldMusloDer = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        lblMusloIzq = new javax.swing.JLabel();
        fieldMusloIzq = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        lblPantorrillaDer = new javax.swing.JLabel();
        fieldPantorrillaDer = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        lblPantorrillaIzq = new javax.swing.JLabel();
        fieldPantorrillaIzq = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        lblPresionArterial = new javax.swing.JLabel();
        lblFrecuenciaCardiaca = new javax.swing.JLabel();
        fieldFreacuenciaCardiaca = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        lblSistolica = new javax.swing.JLabel();
        fieldSistolica = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        lblDiastolica = new javax.swing.JLabel();
        fieldDiastolica = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setIconifiable(true);
        setTitle("Ver Medidas");

        panelAgregarMedidas.setBackground(new java.awt.Color(0, 153, 102));

        lblEstatura.setText("Estatura:");

        jLabel2.setText("Mts");

        lblPeso.setText("Peso:");

        jLabel4.setText("Kg");

        jLabel5.setText("_________________________________________________________________________________");

        lblPliegues.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPliegues.setText("Pliegues Cutáneos");

        lblTricep.setText("Tríceps:");

        fieldTricep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTricepActionPerformed(evt);
            }
        });

        jLabel8.setText("mm");

        lblSubescapular.setText("Subescapular:");

        fieldSubescapular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldSubescapularActionPerformed(evt);
            }
        });

        jLabel10.setText("mm");

        lblAbdomen.setText("Abdomen:");

        fieldAbdomen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAbdomenActionPerformed(evt);
            }
        });

        jLabel12.setText("mm");

        lblIliaco.setText("Iliaco:");

        fieldIliaco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldIliacoActionPerformed(evt);
            }
        });

        jLabel14.setText("mm");

        lblMuslo.setText("Muslo:");

        fieldMuslo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldMusloActionPerformed(evt);
            }
        });

        fieldPectoralH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPectoralHActionPerformed(evt);
            }
        });

        jLabel16.setText("mm");

        jLabel17.setText("mm");

        jLabel18.setText("mm");

        lblPantorrilla.setText("Pantorrilla:");

        lblPectoralH.setText("Pectoral (Solo para hombres):");

        jLabel21.setText("________________________________________________________________________________________________________________");

        lblCircunferencias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCircunferencias.setText("Circunferencias Corporales");

        lblCuello.setText("Cuello:");

        jLabel24.setText("cm");

        lblBicepDer.setText("Bicep Derecho:");

        fieldBicepDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldBicepDerActionPerformed(evt);
            }
        });

        jLabel26.setText("cm");

        lblBicepIzq.setText("Bicep Izquierdo:");

        fieldBicepIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldBicepIzqActionPerformed(evt);
            }
        });

        jLabel28.setText("cm");

        lblPectoral.setText("Pectoral:");

        fieldPectoral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPectoralActionPerformed(evt);
            }
        });

        jLabel30.setText("cm");

        lblEspalda.setText("Espalda:");

        fieldEspalda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEspaldaActionPerformed(evt);
            }
        });

        jLabel32.setText("cm");

        lblCintura1.setText("Cintura1:");

        fieldCintura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCintura1ActionPerformed(evt);
            }
        });

        jLabel34.setText("cm");

        lblCintura2.setText("Cintura2:");

        fieldCintura2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCintura2ActionPerformed(evt);
            }
        });

        jLabel36.setText("cm");

        lblCintura3.setText("Cintura3:");

        fieldCintura3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCintura3ActionPerformed(evt);
            }
        });

        jLabel38.setText("cm");

        lblCadera.setText("Cadera:");

        fieldCadera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCaderaActionPerformed(evt);
            }
        });

        jLabel40.setText("cm");

        lblMusloDer.setText("Muslo Derecho:");

        fieldMusloDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldMusloDerActionPerformed(evt);
            }
        });

        jLabel42.setText("cm");

        lblMusloIzq.setText("Muslo Izquierdo:");

        jLabel44.setText("cm");

        lblPantorrillaDer.setText("Pantorrila Derecha:");

        fieldPantorrillaDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPantorrillaDerActionPerformed(evt);
            }
        });

        jLabel46.setText("cm");

        lblPantorrillaIzq.setText("Pantorrilla Izquierda:");

        fieldPantorrillaIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPantorrillaIzqActionPerformed(evt);
            }
        });

        jLabel48.setText("cm");

        jLabel49.setText("________________________________________________________________________________________________________________");

        lblPresionArterial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPresionArterial.setText("Presión Arterial");

        lblFrecuenciaCardiaca.setText("Frecuencia Cardiaca en reposo:");

        fieldFreacuenciaCardiaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFreacuenciaCardiacaActionPerformed(evt);
            }
        });

        jLabel52.setText("latidos por minuto");

        lblSistolica.setText("Sistólica:");

        jLabel54.setText("mm");

        lblDiastolica.setText("Diastólica:");

        jLabel56.setText("mm");

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/medidas.png"))); // NOI18N

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAgregarMedidasLayout = new javax.swing.GroupLayout(panelAgregarMedidas);
        panelAgregarMedidas.setLayout(panelAgregarMedidasLayout);
        panelAgregarMedidasLayout.setHorizontalGroup(
            panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarMedidasLayout.createSequentialGroup()
                .addGroup(panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgregarMedidasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelAgregarMedidasLayout.createSequentialGroup()
                                .addComponent(lblDiastolica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldDiastolica, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelAgregarMedidasLayout.createSequentialGroup()
                                .addComponent(lblSistolica)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fieldSistolica, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel56)
                            .addComponent(jLabel54))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelAgregarMedidasLayout.createSequentialGroup()
                        .addComponent(lblPresionArterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgregarMedidasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblFrecuenciaCardiaca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldFreacuenciaCardiaca, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel52))
                    .addGroup(panelAgregarMedidasLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(btnSalir)))
                .addGap(196, 196, 196))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarMedidasLayout.createSequentialGroup()
                .addGroup(panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCircunferencias, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAgregarMedidasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCuello)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldCuello, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addComponent(lblBicepDer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldBicepDer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addGap(67, 67, 67)
                        .addComponent(lblBicepIzq)
                        .addGap(18, 18, 18)
                        .addComponent(fieldBicepIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel28)
                        .addGap(18, 18, 18)
                        .addComponent(lblPectoral)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldPectoral, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(60, 60, 60))
            .addGroup(panelAgregarMedidasLayout.createSequentialGroup()
                .addGroup(panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgregarMedidasLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lblEstatura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(54, 54, 54)
                        .addComponent(lblPeso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addGroup(panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelAgregarMedidasLayout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAgregarMedidasLayout.createSequentialGroup()
                                    .addComponent(lblTricep)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fieldTricep, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAgregarMedidasLayout.createSequentialGroup()
                                    .addComponent(lblMuslo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fieldMuslo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel16))
                            .addGap(27, 27, 27)
                            .addGroup(panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPantorrilla)
                                .addComponent(lblSubescapular))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelAgregarMedidasLayout.createSequentialGroup()
                                    .addComponent(fieldSubescapular, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel10))
                                .addGroup(panelAgregarMedidasLayout.createSequentialGroup()
                                    .addComponent(fieldPantorrilla, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel17)))
                            .addGap(32, 32, 32)
                            .addGroup(panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelAgregarMedidasLayout.createSequentialGroup()
                                    .addComponent(lblAbdomen)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fieldAbdomen, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel12)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblIliaco)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fieldIliaco, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel14))
                                .addGroup(panelAgregarMedidasLayout.createSequentialGroup()
                                    .addComponent(lblPectoralH)
                                    .addGap(18, 18, 18)
                                    .addComponent(fieldPectoralH, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel18))))
                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelAgregarMedidasLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panelAgregarMedidasLayout.createSequentialGroup()
                                    .addComponent(lblEspalda)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fieldEspalda, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel32)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblCintura1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fieldCintura1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel34)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblCintura2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fieldCintura2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel36)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblCintura3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fieldCintura3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel38)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblCadera)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fieldCadera, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel40))
                                .addGroup(panelAgregarMedidasLayout.createSequentialGroup()
                                    .addComponent(lblMusloDer)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fieldMusloDer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel42)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblMusloIzq)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fieldMusloIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel44)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblPantorrillaDer)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fieldPantorrillaDer, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel46)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblPantorrillaIzq)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(fieldPantorrillaIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel48))))
                        .addGroup(panelAgregarMedidasLayout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel57))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarMedidasLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblPliegues, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(254, 254, 254))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAgregarMedidasLayout.setVerticalGroup(
            panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarMedidasLayout.createSequentialGroup()
                .addGroup(panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelAgregarMedidasLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEstatura)
                            .addComponent(fieldEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(lblPeso)
                            .addComponent(fieldPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(31, 31, 31)
                        .addComponent(lblPliegues)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTricep)
                            .addComponent(fieldTricep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(lblSubescapular)
                            .addComponent(fieldSubescapular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(lblAbdomen)
                            .addComponent(fieldAbdomen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(lblIliaco)
                            .addComponent(fieldIliaco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAgregarMedidasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel57)
                        .addGap(17, 17, 17)))
                .addGap(22, 22, 22)
                .addGroup(panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMuslo)
                    .addComponent(fieldMuslo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(lblPantorrilla)
                    .addComponent(fieldPantorrilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(lblPectoralH)
                    .addComponent(fieldPectoralH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCircunferencias, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCuello)
                        .addComponent(fieldCuello, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblBicepDer)
                        .addComponent(fieldBicepDer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBicepIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fieldBicepIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPectoral)
                        .addComponent(fieldPectoral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEspalda)
                    .addComponent(fieldEspalda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCintura1)
                    .addComponent(fieldCintura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCintura2)
                    .addComponent(fieldCintura2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCintura3)
                    .addComponent(fieldCintura3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCadera)
                    .addComponent(fieldCadera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMusloDer)
                    .addComponent(fieldMusloDer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMusloIzq)
                    .addComponent(fieldMusloIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPantorrillaDer)
                    .addComponent(fieldPantorrillaDer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPantorrillaIzq)
                    .addComponent(fieldPantorrillaIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgregarMedidasLayout.createSequentialGroup()
                        .addComponent(lblPresionArterial)
                        .addGroup(panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAgregarMedidasLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fieldSistolica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSistolica)
                                    .addComponent(jLabel54))
                                .addGap(18, 18, 18)
                                .addGroup(panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblDiastolica)
                                    .addComponent(fieldDiastolica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel56)))
                            .addGroup(panelAgregarMedidasLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelAgregarMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFrecuenciaCardiaca)
                                    .addComponent(fieldFreacuenciaCardiaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel52))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(btnSalir)))
                        .addContainerGap())
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelAgregarMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAgregarMedidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldFreacuenciaCardiacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFreacuenciaCardiacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFreacuenciaCardiacaActionPerformed

    private void fieldPantorrillaIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPantorrillaIzqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPantorrillaIzqActionPerformed

    private void fieldPantorrillaDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPantorrillaDerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPantorrillaDerActionPerformed

    private void fieldMusloDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldMusloDerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldMusloDerActionPerformed

    private void fieldCaderaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCaderaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCaderaActionPerformed

    private void fieldCintura3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCintura3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCintura3ActionPerformed

    private void fieldCintura2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCintura2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCintura2ActionPerformed

    private void fieldCintura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCintura1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCintura1ActionPerformed

    private void fieldEspaldaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEspaldaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEspaldaActionPerformed

    private void fieldBicepIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldBicepIzqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldBicepIzqActionPerformed

    private void fieldBicepDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldBicepDerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldBicepDerActionPerformed

    private void fieldIliacoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldIliacoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldIliacoActionPerformed

    private void fieldAbdomenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAbdomenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAbdomenActionPerformed

    private void fieldSubescapularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldSubescapularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldSubescapularActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void fieldTricepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTricepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTricepActionPerformed

    private void fieldPectoralHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPectoralHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPectoralHActionPerformed

    private void fieldMusloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldMusloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldMusloActionPerformed

    private void fieldPectoralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPectoralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPectoralActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JTextField fieldAbdomen;
    private javax.swing.JTextField fieldBicepDer;
    private javax.swing.JTextField fieldBicepIzq;
    private javax.swing.JTextField fieldCadera;
    private javax.swing.JTextField fieldCintura1;
    private javax.swing.JTextField fieldCintura2;
    private javax.swing.JTextField fieldCintura3;
    private javax.swing.JTextField fieldCuello;
    private javax.swing.JTextField fieldDiastolica;
    private javax.swing.JTextField fieldEspalda;
    private javax.swing.JTextField fieldEstatura;
    private javax.swing.JTextField fieldFreacuenciaCardiaca;
    private javax.swing.JTextField fieldIliaco;
    private javax.swing.JTextField fieldMuslo;
    private javax.swing.JTextField fieldMusloDer;
    private javax.swing.JTextField fieldMusloIzq;
    private javax.swing.JTextField fieldPantorrilla;
    private javax.swing.JTextField fieldPantorrillaDer;
    private javax.swing.JTextField fieldPantorrillaIzq;
    private javax.swing.JTextField fieldPectoral;
    private javax.swing.JTextField fieldPectoralH;
    private javax.swing.JTextField fieldPeso;
    private javax.swing.JTextField fieldSistolica;
    private javax.swing.JTextField fieldSubescapular;
    private javax.swing.JTextField fieldTricep;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAbdomen;
    private javax.swing.JLabel lblBicepDer;
    private javax.swing.JLabel lblBicepIzq;
    private javax.swing.JLabel lblCadera;
    private javax.swing.JLabel lblCintura1;
    private javax.swing.JLabel lblCintura2;
    private javax.swing.JLabel lblCintura3;
    private javax.swing.JLabel lblCircunferencias;
    private javax.swing.JLabel lblCuello;
    private javax.swing.JLabel lblDiastolica;
    private javax.swing.JLabel lblEspalda;
    private javax.swing.JLabel lblEstatura;
    private javax.swing.JLabel lblFrecuenciaCardiaca;
    private javax.swing.JLabel lblIliaco;
    private javax.swing.JLabel lblMuslo;
    private javax.swing.JLabel lblMusloDer;
    private javax.swing.JLabel lblMusloIzq;
    private javax.swing.JLabel lblPantorrilla;
    private javax.swing.JLabel lblPantorrillaDer;
    private javax.swing.JLabel lblPantorrillaIzq;
    private javax.swing.JLabel lblPectoral;
    private javax.swing.JLabel lblPectoralH;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblPliegues;
    private javax.swing.JLabel lblPresionArterial;
    private javax.swing.JLabel lblSistolica;
    private javax.swing.JLabel lblSubescapular;
    private javax.swing.JLabel lblTricep;
    private javax.swing.JPanel panelAgregarMedidas;
    // End of variables declaration//GEN-END:variables
}
